
[[constraint]]
  name = "github.com/armon/circbuf"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.23.13"

[[constraint]]
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.27.0"
