
[[constraint]]
  name = "github.com/armon/circbuf"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.21.9"

[[constraint]]
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "^6.7.3"
